name = "DataDrivenAcoustics"
uuid = "b376a22e-6432-4b80-a794-261b95783a4a"
authors = ["Li Kexin <kexin@nus.edu.sg> and Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.1.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
